### ISSUE TITLE
Error in message

### ISSUE THREAD

**Issue by cr1m3** [shidec/LINE-Bot-Framework-Apps#1]
i got some errors like this : 
error line 17 in GuessTheLogo.php
`$text = ($message['text']);`
and then, fix it with isset
`$text = (isset($message['text']));`
do it in all apps script and done.

But, i still get error in AnonimChatBot.php

Any solution?

**Comment by shidec** [comment]
Bug fixed on https://github.com/shidec/line_bot_framework

**Comment by shidec** [comment]
Anonymous Chat & TicTacToe apps can not be tested on Emulator, because emulator does not support push message.

**Comment by cr1m3** [comment]
> 
> 
> Bug fixed on https://github.com/shidec/line_bot_framework

Thx 👍
